Repository Rapteon/thecampuscookbook, pull requests merged in 2025-03, with the labels that each got.

#3 Adding models and related setup code in models.py,settings.py and url…
  thecampuscookbook/thecampuscookbook/models.py
  thecampuscookbook/thecampuscookbook/settings.py
  thecampuscookbook/thecampuscookbook/urls.py
Labels: enhancement

#5 Added models for Recipe, Rating, and Category.
  thecampuscookbook/account/admin.py
  thecampuscookbook/account/migrations/0001_initial.py
  thecampuscookbook/account/migrations/__init__.py
  thecampuscookbook/account/models.py
  thecampuscookbook/category/admin.py
  thecampuscookbook/category/migrations/0001_initial.py
  thecampuscookbook/category/models.py
  thecampuscookbook/data-populator.py
Labels: enhancement

#10 Show 2 most-recently added recipes on the home page
  thecampuscookbook/account/migrations/0002_remove_recipe_category_id_remove_recipe_user_id.py
  thecampuscookbook/account/migrations/0003_alter_rating_recipe_id_remove_savedrecipe_recipe_id_and_more.py
  thecampuscookbook/account/models.py
  thecampuscookbook/data-populator.py
  thecampuscookbook/home/views.py
  thecampuscookbook/media/.gitkeep
  thecampuscookbook/media/images/recipes/easy-apple-crumble.jpeg
  thecampuscookbook/media/images/recipes/garlic-butter-noodles-with-chicken.jpeg
  thecampuscookbook/media/images/recipes/grilled-vegetable-antipasti.jpeg
  thecampuscookbook/media/images/recipes/miso-glazed-salmon-with-stir-fried-noodles.jpeg
  thecampuscookbook/media/images/recipes/mizo-glazed-salmon-with-stir-fried-noodles.jpeg
  thecampuscookbook/media/images/recipes/norwegian-fiskesuppe.jpeg
  thecampuscookbook/media/images/recipes/slow-cooker-creamy-chicken-soup.jpeg
  thecampuscookbook/media/images/recipes/spiced-harissa-chickpea-soup.jpeg
  thecampuscookbook/media/images/recipes/sumac-chicken-flatbreads-with-mint-yogurt.jpeg
  thecampuscookbook/media/images/recipes/sweet-and-spicy-turkey-sandwich.jpeg
  thecampuscookbook/media/images/recipes/tomato-soup.jpeg
  thecampuscookbook/recipe/__init__.py
  thecampuscookbook/recipe/admin.py
  thecampuscookbook/recipe/apps.py
  thecampuscookbook/recipe/migrations/0001_initial.py
  thecampuscookbook/recipe/migrations/__init__.py
  thecampuscookbook/recipe/models.py
  thecampuscookbook/recipe/tests.py
  thecampuscookbook/recipe/views.py
  thecampuscookbook/templates/category/index.html
  thecampuscookbook/templates/home/index.html
  thecampuscookbook/thecampuscookbook/settings.py
  thecampuscookbook/thecampuscookbook/urls.py
Labels: enhancement

#13 Changes made by Sibu for the profile page.
  thecampuscookbook/static/css/account.css
  thecampuscookbook/static/css/base.css
  thecampuscookbook/static/css/category.css
  thecampuscookbook/static/css/footer.css
  thecampuscookbook/static/css/home.css
  thecampuscookbook/static/css/login.css
  thecampuscookbook/static/css/navbar.css
  thecampuscookbook/static/css/register.css
  thecampuscookbook/static/js/navb.js
  thecampuscookbook/static/js/recipe-modal.js
  thecampuscookbook/templates/account/add-recipes/index.html
  thecampuscookbook/templates/account/base.html
  thecampuscookbook/templates/account/my-recipes/index.html
  thecampuscookbook/templates/account/saved-recipes/index.html
  thecampuscookbook/templates/account/settings/index.html
Labels: bug

#18 refactoring accounts code
  thecampuscookbook/static/css/account.css
  thecampuscookbook/templates/account/add-recipes/index.html
  thecampuscookbook/templates/account/base.html
  thecampuscookbook/templates/account/my-recipes/index.html
  thecampuscookbook/templates/account/saved-recipes/index.html
  thecampuscookbook/templates/account/settings/index.html
Labels: bug

#19 Implemented user registration.
  thecampuscookbook/account/admin.py
  thecampuscookbook/account/migrations/0004_userprofile_delete_rating.py
  thecampuscookbook/account/migrations/0005_alter_userprofile_options.py
  thecampuscookbook/account/models.py
  thecampuscookbook/category/views.py
  thecampuscookbook/data-populator.py
  thecampuscookbook/media/images/avatars/SIMD_map.png
  thecampuscookbook/media/images/avatars/admin.png
  thecampuscookbook/media/images/avatars/jane-doe.png
  thecampuscookbook/media/images/avatars/john-doe.png
  thecampuscookbook/recipe/admin.py
  thecampuscookbook/recipe/migrations/0002_rename_recipe_id_savedrecipe_recipe_and_more.py
  thecampuscookbook/recipe/migrations/0003_rename_recipe_id_rating_recipe.py
  thecampuscookbook/recipe/models.py
  thecampuscookbook/register/forms.py
  thecampuscookbook/register/views.py
  thecampuscookbook/templates/register/register.html
  thecampuscookbook/thecampuscookbook/urls.py
Labels: enhancement

#24 Merged changes provided by Alexa (partially) and added support…
  thecampuscookbook/account/urls.py
  thecampuscookbook/login/views.py
  thecampuscookbook/media/images/avatars/SIMD_map.png
  thecampuscookbook/templates/category/base.html
  thecampuscookbook/templates/category/index.html
  thecampuscookbook/templates/global/footer/footer.html
  thecampuscookbook/templates/global/navbar/navbar.html
  thecampuscookbook/templates/home/index.html
  thecampuscookbook/templates/login/login.html
  thecampuscookbook/templates/register/register.html
  thecampuscookbook/thecampuscookbook/urls.py
Labels: bug, enhancement

#25 Added login_required decorator for some views and restricted page.
  thecampuscookbook/account/views.py
  thecampuscookbook/login/views.py
  thecampuscookbook/static/css/restricted.css
  thecampuscookbook/templates/login/restricted.html
  thecampuscookbook/thecampuscookbook/urls.py
Labels: enhancement

#27 adding pagination fix saved recipe
  thecampuscookbook/account/views.py
  thecampuscookbook/static/css/account.css
  thecampuscookbook/templates/account/saved-recipes/index.html
Labels: bug

#30 Feature category templates
  thecampuscookbook/static/images/dessert.jpeg
  thecampuscookbook/static/images/hero-home.jpg
  thecampuscookbook/static/images/main.jpeg
  thecampuscookbook/static/images/soup.jpeg
  thecampuscookbook/static/images/starter.jpeg
  thecampuscookbook/templates/category/creative/index.html
  thecampuscookbook/templates/category/dessert/index.html
  thecampuscookbook/templates/category/main/index.html
  thecampuscookbook/templates/category/soup/index.html
  thecampuscookbook/templates/category/starter/index.html
Labels: bug

#31 adding testcases
  thecampuscookbook/account/tests.py
  thecampuscookbook/category/tests.py
  thecampuscookbook/recipe/tests.py
Labels: enhancement

#32 Feature category templates
  thecampuscookbook/data-populator.py
  thecampuscookbook/static/css/register.css
  thecampuscookbook/templates/global/footer/footer.html
  thecampuscookbook/templates/login/login.html
  thecampuscookbook/templates/register/register.html
Labels: bug, enhancement

#34 Implemented feature to rate a recipe.
  thecampuscookbook/recipe/urls.py
  thecampuscookbook/recipe/views.py
  thecampuscookbook/static/js/recipe-modal.js
  thecampuscookbook/templates/global/headTag/head-tag.html
  thecampuscookbook/thecampuscookbook/urls.py
Labels: enhancement

#36 adding category pages pagination code
  thecampuscookbook/category/views.py
  thecampuscookbook/templates/category/base.html
  thecampuscookbook/templates/category/index.html
Labels: bug

#37 Added feature to save recipe for a user.
  thecampuscookbook/recipe/urls.py
  thecampuscookbook/recipe/views.py
  thecampuscookbook/static/js/recipe-modal.js
Labels: enhancement

#39 adding remove functionality in saved recipes
  thecampuscookbook/recipe/urls.py
  thecampuscookbook/recipe/views.py
  thecampuscookbook/static/js/account.js
  thecampuscookbook/templates/account/base.html
  thecampuscookbook/templates/account/saved-recipes/index.html
Labels: enhancement

#44 Fixed bug wherein rating was not updated in card after rating.
  thecampuscookbook/recipe/urls.py
  thecampuscookbook/recipe/views.py
  thecampuscookbook/static/js/recipe-modal.js
  thecampuscookbook/templates/category/index.html
Labels: bug

#45 Fixed avatar in profile settings.
  thecampuscookbook/static/css/account.css
  thecampuscookbook/templates/account/base.html
Labels: bug

#46 Added favicon for the website.
  thecampuscookbook/static/favicon.ico
  thecampuscookbook/templates/global/headTag/head-tag.html
Labels: bug

#47 Implemented feature to delete recipes from my-recipes.
  thecampuscookbook/recipe/urls.py
  thecampuscookbook/recipe/views.py
  thecampuscookbook/static/css/account.css
  thecampuscookbook/static/js/account.js
  thecampuscookbook/templates/account/my-recipes/index.html
Labels: enhancement

#48 Fixed bug with mobile navbar items.
  thecampuscookbook/static/js/navb.js
  thecampuscookbook/templates/global/navbar/navbar.html
Labels: bug

#49 Formatted some unformatted files.
  thecampuscookbook/account/tests.py
  thecampuscookbook/account/views.py
  thecampuscookbook/category/tests.py
  thecampuscookbook/category/views.py
  thecampuscookbook/recipe/admin.py
  thecampuscookbook/recipe/tests.py
Labels: config
